export const RESET_STOPWATCH = 'RESET_STOPWATCH';
export const STOP_STOPWATCH = 'STOP_STOPWATCH';
export const START_LAP_TIMER = 'START_LAP_TIMER';
export const STOPWATCH_START = 'STOPWATCH_START';
export const SET_STOPWATCH_TIME = 'SET_STOPWATCH_TIME';
export const STOPWATCH_FIRST_START = 'STOPWATCH_FIRST_START';
export const SET_LAP_TIME = 'SET_LAP_TIME';

export const CHANGE_POMODORO = 'CHANGE_POMODORO';
export const RESET_POMODORO = 'RESET_POMODORO';
export const STOP_POMODORO = 'STOP_POMODORO';
export const POMODORO_START = 'POMODORO_START';
export const POMODORO_FINISHED = 'POMODORO_FINISHED';
export const POMODORO_CYCLE_END = 'POMODORO_CYCLE_END';

export const CHANGE_TIMER = 'CHANGE_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const SET_FIRST_START = 'SET_FIRST_START';
export const PAUSE_TIMER = 'PAUSE_TIMER';
export const TIMER_START = 'TIMER_START';
export const TIMER_CYCLE_END = 'TIMER_CYCLE_END';
